#!/usr/bin/env bash
#----------------------------------------------------------------------------------------------------
# This script loops through each folder in the moosetools repository (package) and runs python
# unittest discover on the "tests" directory within it, if it exists. It also collects coverage
# information from each package.
#----------------------------------------------------------------------------------------------------

# Minimum percent coverage allowed for each package
MIN_COVERAGE=60

# Global exit status
declare -i STATUS=-0

# Function for running tests and reporting coverage
run_python_unit_tests(){
  echo =====================================================================================
  echo RUNNING TESTS: "${1}"
  echo -------------------------------------------------------------------------------------
  coverage run --omit "${1}/**" --include "${1}/../**" -m unittest discover --verbose --start-directory ${1}
  STATUS+=$?
  coverage report --fail-under=${MIN_COVERAGE}
  STATUS+=$?
  echo -e "\n\n"
}

for PACKAGE in */; do
    TESTS_DIR=${PACKAGE}tests
    if [ -d ${TESTS_DIR} ]; then
        run_python_unit_tests ${TESTS_DIR}
    fi
done

exit $(( ${STATUS} > 0 ))
