#!/usr/bin/env bash
#----------------------------------------------------------------------------------------------------
# This script loops through each folder in the moosetools repository (package) and runs python
# unittest discover on the "tests" directory within it, if it exists. It also collects coverage
# information from each package.
#----------------------------------------------------------------------------------------------------

# Minimum percent coverage allowed for each package
MIN_COVERAGE=50

# Global exit status
declare -i STATUS=-0

# Set the PYTHONPATH to the top-level
export PYTHONPATH=$PWD

# Function for running local run_tests script
run_local_python_unit_tests(){
  echo =====================================================================================
  echo RUNNING: "${1}"/run_tests
  echo -------------------------------------------------------------------------------------
  (cd ${1} && ./run_tests)
  STATUS+=$?
  echo -e "\n\n"
}

for PACKAGE in moosetools/*/; do
    TESTS_DIR=${PACKAGE}tests
    if [ -f ${TESTS_DIR}/../run_tests ]; then
        run_local_python_unit_tests ${TESTS_DIR}/..
    fi
done

exit $(( ${STATUS} > 0 ))
